---
std_msgs/Header header

# How big each "pixel" in the map is.
float32 resolution

# Width is along the x axis and height is along the y axis.
uint32 width
uint32 height

# The location of the "origin" (upper left point) of the image. This refers to
# the "upper-left" of the upper left most pixel as well.
geometry_msgs/Point origin

# canvas_width is along the x axis and canvas_height is along the y axis.
uint32 canvas_width
uint32 canvas_height

# Pixel coordinates of the upper left most pixel of the drawing area w.r.t the whole image.
uint32 canvas_leftmost_pixel
uint32 canvas_uppermost_pixel

# Which value is used for "unknown" cells.
float32 unknown_value

# Data is stored as floats since it's a distance map.
float32[] data